In [24]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [33]:
def unistats(df):
    output_df = pd.DataFrame(columns=["Count", "Missing", "Unique", "Dtype",
                                     "Mean", "Mode", "Min", "25%", "Median",
                                     "75%", "Max", "Std", "Skew", "Kurtosis"])
    
    for col in df:
        if pd.api.types.is_numeric_dtype(df[col]):
            output_df.loc[col] = [df[col].count(), df[col].isnull().sum(), 
                                  df[col].nunique(), df[col].dtype, df[col].mean(), 
                                  df[col].mode().values[0], df[col].min(), 
                                  df[col].quantile(0.25), df[col].median(), 
                                  df[col].quantile(0.75), df[col].max(), df[col].std(), 
                                  df[col].skew(), df[col].kurt()]
        else:
            output_df.loc[col] = [df[col].count(), df[col].isnull().sum(), 
                                  df[col].nunique(), df[col].dtype, 
                                  "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"]
    
    return output_df

# Test the function
# pd.set_option("display.max_rows", 100)
# pd.set_option("display.max_columns", 100)
unistats(df)

,Count,Missing,Unique,Dtype,Mean,Mode,Min,25%,Median,75%,Max,Std,Skew,Kurtosis
Id,1460,0,1460,int64,730.5,1,1,365.75,730.5,1095.25,1460,421.610009,0.0,-1.2
MSSubClass,1460,0,15,int64,56.89726,20,20,20.0,50.0,70.0,190,42.300571,1.407657,1.580188
MSZoning,1460,0,5,object,-,-,-,-,-,-,-,-,-,-
LotFrontage,1201,259,110,float64,70.049958,60.0,21.0,59.0,69.0,80.0,313.0,24.284752,2.163569,17.452867
LotArea,1460,0,1073,int64,10516.828082,7200,1300,7553.5,9478.5,11601.5,215245,9981.264932,12.207688,203.243271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MoSold,1460,0,12,int64,6.321918,6,1,5.0,6.0,8.0,12,2.703626,0.212053,-0.404109
YrSold,1460,0,5,int64,2007.815753,2009,2006,2007.0,2008.0,2009.0,2010,1.328095,0.096269,-1.190601
SaleType,1460,0,9,object,-,-,-,-,-,-,-,-,-,-
SaleCondition,1460,0,6,object,-,-,-,-,-,-,-,-,-,-
SalePrice,1460,0,663,int64,180921.19589,140000,34900,129975.0,163000.0,214000.0,755000,79442.502883,1.882876,6.536282